name: Build Monkey

on:
  push:
    paths:
      - "**.go"

defaults:
  run:
    working-directory: ./src/monkey

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          cache: false
          go-version: "1.20"

      - name: Compile
        run: go build -v

      - name: Lexer testing
        run: go test -v ./lexer

      - name: Parser testing
        run: go test -v ./parser

      - name: AST testing
        run: go test -v ./ast

      - name: Object testing
        run: go test -v ./object

      - name: Evaluator testing
        run: go test -v ./evaluator
