name: Build Monkey

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: ./src/monkey

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Compile
        run: go build

      - name: Lexer testing
        run: go test ./lexer

      - name: Parser testing
        run: go test ./parser

      - name: AST testing
        run: go test ./ast
